const {hashKey, validateKey} = require('./key')
const {PropertyValidationError} = require('../../shared/errors')
const {getTodaysDate} = require('../../shared/dateUtils')

// Validate & hash API key
const processKey = key => {
    const validKey = validateKey(key)
    return hashKey(validKey)
}

// src: https://masteringjs.io/tutorials/mongoose/mongoose-validate-unique-email
const validateEmail = email => {
    // todo: figure out why eslint is complaining and fix it
    // eslint-disable-next-line no-useless-escape
    const emailRegex = /.+\@.+\..+/
    if(!email || !emailRegex.test(email))
        throw new PropertyValidationError('email', 'Email fails validation tests')

    return email
}

/**
 * Create API consumer POJO
 * @param {string} key - API key generated by genKey()
 * @param {string} email - email for new API consumer
 */
module.exports = function(key, email){
    this.key = processKey(key)
    this.email = validateEmail(email)
    this.accessDate = getTodaysDate()
    this.usage = 0
}